version: "3"

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: gotodo
  gotodo-backend:
    build:
      context: .
    environment:
      DB_ENGINE: POSTGRES
      DB_DSN: host=postgres user=$DB_USER password=$DB_PASSWORD sslmode=disable
      GIN_MODE: release
    depends_on:
      - postgres
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx/index.html:/var/www/index.html
      - ./nginx/local.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - gotodo-backend
